#!/bin/bash
ip="$(terraform show -json | jq -r '.values.root_module.resources[] | .values.public_ip_address'  | grep -v null)"
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null azureuser@$ip
