#cloud-config
bootcmd:
  - "mkdir -p /etc/td-agent-bit/conf.d"
  - "mkdir -p /opt/td-agent-bit/scripts"

apt:
  sources:
    fluent-bit.list:
      source: "deb https://packages.fluentbit.io/ubuntu/focal focal main"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1
        
        mQENBFXlAtMBCAC7SievUBw7WTm9yWCp+Wfo28w7A7ERVJpZp3sTw5Wn+gISHA+1
        iCkfG0UDDo0smWQb+zZ6spd2OV2zg/TTgSjZb0JJiCeIrzFtWctkm8zS7X7g3t+0
        a92IYYL/yA9x2RP7DaszqqT90GIoMZ18Iu1qwe651rOhAtNCrcmw5lsa+rrHDUVH
        tIH2EH/71akkxnlLB9jFknQ+8nDAkX2btByG0KYr+i7a2FmSFo+CKYZewauanriU
        cPTQHHFmapKyEDLbE1DlTku+9IqhxakwTyUn9bCnhUMWEzqmpfZWS/FzcclBIsWC
        SFZv4LLNbYMaIX2jwGI7umUuQ4GttDZS/6+fABEBAAG0KUVkdWFyZG8gU2lsdmEg
        PGVkdWFyZG9AdHJlYXN1cmUtZGF0YS5jb20+iQE3BBMBCAAhAhsDAh4BAheABQJX
        fIHPBQsJCAcDBRUKCQgLBRYCAwEAAAoJEE/4NotuoHIqeAwIAIAsyO6sV/W4xUro
        XzYntfEvjcgVrR1DnZMLN/zkGbgv1AfoRLfOW/9pBDpIJAiifzYBr265zoKf7Wny
        D99KN7N9NTf1lgzoDFgWdCltvUzKNj0D8xN1cTvUq0tGxpEFBCtbjg3swW68etJx
        wkFhPXewcgbVk2PYz3AK7PDcR1A3HRZc/hI1GqfxoxYLT6qmXEE9/0ZI7cIvoYjp
        S66QXnpSHDZ7thROEbQCwIvZh0usVaSa7HGzW6YLwq7Mtk36eRYXMOkl3tRlu3Me
        KuD0vWrvHIBVU1C5GLSvK+K2O0dx9MgiwbuVegWCZUe56JsTH7THCozvKgcVF3yK
        Wc6gKlO5AQ0EVeUC0wEIAKyJwOGZOTmh45i29c5gxvFB95lu4ajTa9X1zmaM7Xe3
        2VhrLyaIp9noWE8xjv2i97wV9LrzrmUSxzhqSE8MG+qPxy6/PCdxe3kLB+PCvutO
        4EnLy3MnglK6YPSZrxV69nbnO+Ts0dhYWFUqsdE7jwrr6DgED49MUUbzj4y+MPQt
        ljEr69p4pja4VilgqMDWurnQ8M0tnALJHL4kvcWbSwWSAahhYT7HNvtyiXt3U/Na
        Dbaw86L8ENTxXkS5YgiQbm8PLVrfoNzw/z37QVYf4izNpVaqek82TBp0A3FVfVd3
        V7dObzvLDlEEX4kjEbhZYRAK2k74oazE3343ibPwIPUAEQEAAYkBHwQYAQIACQUC
        VeUC0wIbDAAKCRBP+DaLbqByKm0GCACqMPKFdEdEQnmEJ1cTtwx4ax3HUML3frJW
        /Kz4DytGpAD6yq7lLT5BRK2X6QNla+jezDSNfsOw9uPMDhV0iXw/hGpt3kr5wp4J
        UT1LKfkd/0WHgygvLZUobmqkvpqTIKrp5yjAv6WGQpJyTZDcL0D5TsgLr6NC0taJ
        I41ckHWc9Nd3kTS6oVNLngEVDaQ2AezYpHgXgww6XEb60wGvnj/3P0Cx1gvo+V0c
        JIs2r6TYHNdrZKfY6ynxS08Is+axvSdUxoUL27CQ+/ljhkGD2qNyieY9feYRGx+A
        POR1LlqgIS3UH36y9XojJsBF9Qki/3+GG2u//pBiVNSwb6hRtcPF
        =RrLa
        -----END PGP PUBLIC KEY BLOCK-----

packages:
  - td-agent-bit

write_files:
  - path: /opt/td-agent-bit/scripts/append_tag.lua
    content: |
      function append_tag(tag, timestamp, record)
          new_record = record
          new_record["tag"] = tag
          return 1, timestamp, new_record
      end
    permissions: '0755'
    owner: 'root:root'
  - path: /etc/td-agent-bit/my.conf
    content: |
      @SET OU=makerun
      [SERVICE]
          flush           5
          daemon          Off
          log_level       info
          parsers_file    parsers.conf
          plugins_file    plugins.conf
          http_server     Off
          http_listen     0.0.0.0
          http_port       2020
          storage.metrics on
      [INPUT]
          name     tail
          parser   isotimestamp-singleline
          tag      app.sourcetype
          path     /tmp/test.log
          db       /tmp/fluentbit.db
          path_key source
      [FILTER]
          name  rewrite_tag
          match app.*
          rule  $source ^(.*)$ out.app.$${OU}.$TAG[1].$${HOSTNAME} false
      [FILTER]
          name   lua
          match  out.*
          script /opt/td-agent-bit/scripts/append_tag.lua
          call   append_tag
      [OUTPUT]
          name                          kafka
          match                         out.*
          brokers                       ${eventhubNS}.servicebus.windows.net:9093
          topics                        ${eventhub}
          rdkafka.security.protocol     SASL_SSL
          rdkafka.sasl.mechanism        PLAIN
          rdkafka.sasl.username         $ConnectionString
          rdkafka.sasl.password         ${connectionString}
          rdkafka.request.required.acks 1
          rdkafka.log.connection.close  false
          rdkafka.compression.codec     none
    permissions: '0640'
    owner: 'root:root'
