#cloud-config
hostname: test1

bootcmd:
  - "mkdir -p /etc/fluent-bit/parsers.d"
  - "mkdir -p /etc/fluent-bit/filters.d"
  - "mkdir -p /etc/fluent-bit/inputs.d"
  - "mkdir -p /etc/fluent-bit/outputs.d"

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOlY9F0gLlOTPvf5XrAiXH+qGdtrNuEL6Lbd+I1TFTzpci97ozzZksJ/6GvBnC/iX1WObibQBGZNdDdnD7041kbwnfgxNn9gC/EckNgRSmMmVFN/7QkPVclcCgBDqMeKo/r7k8PZFHi8cEUeJX71Bzac4cnRgN5jQY/cp6+MN+CcN44xyP1Lubjv+tfKmfLU7wzOLVcV6TnywpCPSC/yDAVfzhy/usNxlLnejtChhAuy98v1ibKkpWXKd3LbKvl2CHDA464dHvLS7zyoB/wOfjBgCXYkjWhq+lUE/EVDAhlp5k8+HGRmGY5mcB8wvUUvZw1wfy3NyR0pf3n6G1nA5B"

write_files:
  - path: /etc/fluent-bit/identity
    permissions: '0640'
    owner: 'root:root'
    content: |
      OU=makerun
  - path: /etc/fluent-bit/inputs.d/example.conf
    permissions: '0640'
    owner: 'root:root'
    content: |
      [INPUT]
          name     tail
          parser   isotimestamp-singleline
          tag      app.sourcetype
          path     /tmp/test.log
          db       /tmp/fluentbit.db
          path_key source
  - path: /etc/fluent-bit/filters.d/kafka_tagging.conf
    permissions: '0640'
    owner: 'root:root'
    content: |
      [FILTER]
          name  rewrite_tag
          match app.*
          rule  $source ^(.*)$ out.app.$${OU}.$TAG[1].$${HOSTNAME} false
      [FILTER]
          name   lua
          match  out.*
          script /opt/fluent-bit/bin/append_tag.lua
          call   append_tag
  - path: /etc/fluent-bit/parsers.d/isotime-singleline.conf
    permissions: '0640'
    owner: 'root:root'
    content: |
      [PARSER]
          Name isotimestamp-singleline
          Format regex
          Regex ^(?<time>\S+) (?<log>.*)
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
          Time_Keep   On
  - path: /etc/fluent-bit/outputs.d/to_kafka.conf
    permissions: '0640'
    owner: 'root:root'
    content: |
      [OUTPUT]
          name                          kafka
          match                         out.*
          brokers                       ${eventhubNS}.servicebus.windows.net:9093
          topics                        ${eventhub}
          rdkafka.security.protocol     SASL_SSL
          rdkafka.sasl.mechanism        PLAIN
          rdkafka.sasl.username         $ConnectionString
          rdkafka.sasl.password         ${connectionString}
          rdkafka.request.required.acks 1
          rdkafka.log.connection.close  false
          rdkafka.compression.codec     none

